apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: LoadBalancer  # Change to NodePort if you prefer
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # You can pick any available port
