
      
apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
spec:
  selector:
    app: dispatcher
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 31239
